// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0gqyPJSVGm6A5dK_Zoauu0fIvSvxsGY',
    appId: '1:598176529620:web:764e1fcafeeebd78f1cf41',
    messagingSenderId: '598176529620',
    projectId: 'islingtontest',
    authDomain: 'islingtontest.firebaseapp.com',
    storageBucket: 'islingtontest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHguxAOF2t8X-0ZKqRcp4tsfUj-myyudc',
    appId: '1:598176529620:android:f1196660b64f134cf1cf41',
    messagingSenderId: '598176529620',
    projectId: 'islingtontest',
    storageBucket: 'islingtontest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DIirHMNyToKaid-uAPAWdncsNdPL0gs',
    appId: '1:598176529620:ios:f94e74f8718bc42bf1cf41',
    messagingSenderId: '598176529620',
    projectId: 'islingtontest',
    storageBucket: 'islingtontest.appspot.com',
    iosClientId:
        '598176529620-d2j7ocj2k339k4hftq0q05ttla68k8nu.apps.googleusercontent.com',
    iosBundleId: 'com.bimaly.islingtoncollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1DIirHMNyToKaid-uAPAWdncsNdPL0gs',
    appId: '1:598176529620:ios:f94e74f8718bc42bf1cf41',
    messagingSenderId: '598176529620',
    projectId: 'islingtontest',
    storageBucket: 'islingtontest.appspot.com',
    iosClientId:
        '598176529620-d2j7ocj2k339k4hftq0q05ttla68k8nu.apps.googleusercontent.com',
    iosBundleId: 'com.bimaly.islingtoncollege',
  );
}
